package com.example.chattyio.entity;
// Generated Jan 23, 2024 10:46:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductPriceHistory generated by hbm2java
 */
@Entity
@Table(name="product_price_history"
    ,catalog="antipattern"
)
public class ProductPriceHistory  implements java.io.Serializable {


     private Integer id;
     private Integer price;
     private Date createdAt;
     private Integer productId;

    public ProductPriceHistory() {
    }

    public ProductPriceHistory(Integer price, Date createdAt, Integer productId) {
       this.price = price;
       this.createdAt = createdAt;
       this.productId = productId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="price")
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    
    @Column(name="product_id")
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }




}


