package com.example.chattyio.entity;
// Generated Jan 23, 2024 10:46:56 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product"
        , catalog = "antipattern"
)
public class Product implements java.io.Serializable {


    private Integer id;
    private String name;

    private Category category;
    private Set<PriceHistory> priceHistories;

    public Product() {
    }

    public Product(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(mappedBy = "product", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    public Set<PriceHistory> getPriceHistories() {
        return priceHistories;
    }

    public void setPriceHistories(Set<PriceHistory> priceHistories) {
        this.priceHistories = priceHistories;
    }

    @ManyToOne
    @JoinColumn(name = "category_id")
    @JsonIgnore
    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    @Override
    public String toString() {
        return "Product{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }
}


