package com.example.chattyio.entity;
// Generated Jan 23, 2024 10:46:56 PM by Hibernate Tools 4.3.1


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

/**
 * ProductSubCategory generated by hbm2java
 */
@Entity
@Table(name="product_sub_category"
    ,catalog="antipattern"
)
public class ProductSubCategory  implements java.io.Serializable {


     private Integer id;
     private String name;

    private List<Product> products;

    public ProductSubCategory() {
    }

    public ProductSubCategory(String name) {
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @OneToMany()
    public List<Product> getProducts() {
        return products;
    }

    public void setProducts(List<Product> products) {
        this.products = products;
    }
}


